targets:
  $default:
    builders:
      fields_generator|member_count:
        generate_for:
          - lib/library_source.dart
      fields_generator|property_sum:
        generate_for:
          - lib/*.dart
      fields_generator|property_product:
        generate_for:
          - lib/*.dart
      # The end-user of a builder which applies "source_gen|combining_builder"
      # may configure the builder to ignore specific lints for their project
      source_gen|combining_builder:
        options:
          ignore_for_file:
          - lint_a
          - lint_b
