name: example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  fields_generator:
    path: ../fields_generator

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^2.0.0
  test: ^1.5.1

dependency_overrides:
  source_gen: ^1.5.0