name: example
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  fields_generator:
    path: ../
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
