builders:
  property_fields:
    import: "package:fields_generator/builder.dart"
    builder_factories: ["fieldsBuilder"]
    build_extensions: { ".dart": ["fields.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
