name: fields_generator
version: 0.0.2
description: Fields name generator for Dart
homepage: https://github.com/masreplay/fields_generator

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0

  json_annotation: ^4.8.1
  change_case: ^2.0.1
  meta: ^1.12.0
  source_helper: ^1.3.4

dev_dependencies:
  build_runner: ^2.4.8