name: fields_generator
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0

  json_annotation: ^4.8.1
  change_case: ^2.0.1

dev_dependencies:
  build_runner: ^2.4.8